description: Young Parent Payment - weekly rate
metadata:
  unit: currency
  type: value
  reference:
    2018-11-26:
      title: Social Security Act 2018 (As Enacted)
      href: https://www.legislation.govt.nz/act/public/2018/0032/latest/whole.html#DLM6784883
    2019-02-25:
      title: Social Security (Rates of Benefits and Allowances) Order 2019
      href: https://www.legislation.govt.nz/regulation/public/2019/0027/latest/LMS156275.html
    2020-02-24:
      title: Social Security (Rates of Benefits and Allowances) Order 2020
      href: https://www.legislation.govt.nz/regulation/public/2020/0013/latest/whole.html
    2021-02-22:
      title: Social Security (Rates of Benefits and Allowances) Order 2021
      href: https://www.legislation.govt.nz/regulation/public/2021/0015/latest/whole.html
    2022-02-21:
      title: Social Security (Rates of Benefits and Allowances) Order 2022
      href: https://www.legislation.govt.nz/regulation/public/2022/0028/latest/whole.html
    2023-02-20:
      title: Social Security (Rates of Benefits and Allowances) Order 2023
      href: https://www.legislation.govt.nz/regulation/public/2023/0038/latest/whole.html
clauses:
  clause_1_a:
    values:
      2018-11-26:
        value: 334.05
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a) - single with dependent children
            href: https://www.legislation.govt.nz/act/public/2018/0032/latest/DLM6784883.html
      2019-04-01:
        value: 339.69
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a)
            href: https://www.legislation.govt.nz/regulation/public/2019/0027/latest/whole.html
      2020-04-01:
        value: 375.17
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a)
            href: https://www.legislation.govt.nz/regulation/public/2020/0049/latest/whole.html
      2021-04-01:
        value: 386.78
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a)
            href: https://www.legislation.govt.nz/regulation/public/2021/0015/latest/whole.html
      2021-07-01:
        value: 406.78
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a)
            href: https://www.legislation.govt.nz/regulation/public/2021/0120/latest/whole.html
      2022-04-01:
        value: 440.96
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a)
            href: https://www.legislation.govt.nz/regulation/public/2022/0028/latest/whole.html
      2023-04-01:
        value: 472.79
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a)
            href: https://www.legislation.govt.nz/regulation/public/2023/0038/latest/whole.html
      2024-04-01:
        value: 494.80
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(a)
            href: https://www.legislation.govt.nz/regulation/public/2024/0011/latest/whole.html
  clause_1_b:
    values:
      2018-11-26:
        value: 179.44
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b) - in a relationship (rate per person)
            href: https://www.legislation.govt.nz/act/public/2018/0032/latest/DLM6784883.html
      2019-04-01:
        value: 182.47
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b)
            href: https://www.legislation.govt.nz/regulation/public/2019/0027/latest/whole.html
      2020-04-01:
        value: 200.60
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b)
            href: https://www.legislation.govt.nz/regulation/public/2020/0049/latest/whole.html
      2021-04-01:
        value: 206.81
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b)
            href: https://www.legislation.govt.nz/regulation/public/2021/0015/latest/whole.html
      2021-07-01:
        value: 226.81
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b)
            href: https://www.legislation.govt.nz/regulation/public/2021/0120/latest/whole.html
      2022-04-01:
        value: 268.00
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b)
            href: https://www.legislation.govt.nz/regulation/public/2022/0028/latest/whole.html
      2023-04-01:
        value: 287.35
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b)
            href: https://www.legislation.govt.nz/regulation/public/2023/0038/latest/whole.html
      2024-04-01:
        value: 300.73
        metadata:
          reference:
            title: Schedule 4, Part 7, Clause 1(b)
            href: https://www.legislation.govt.nz/regulation/public/2024/0011/latest/whole.html
